---
title: "Project Proposal for CMP595"
author: "Camil Samer Zahlan Redwan"
date: "November 8, 2018"
output:
  pdf_document: default
  html_document: default
---

# Porto Alegre Meteorological Data

The *Instituto Nacional de Meteorologia*, the brazilian national meteorological institute,
subordinate to the Ministério da Agricultura, Pecuária e Abastecimento, provides extensive
meteorological data in a municipal bases. The dataset used in this project consists of
the Porto Alegre meteorological data gathered by a conventional meteorological station.
The meteorological data of Porto Alegre and many more brazilian cities can be downloaded in [**BDMEP**](http://www.inmet.gov.br/portal/index.php?r=bdmep/bdmep) (http://www.inmet.gov.br/portal/index.php?r=bdmep/bdmep). It only requires a free account subscription.

This database shows information from 01/01/1961 to 31/07/2018 in a daily bases and consists
of 38629 rows and 11 columns. Each row consists of the observations of the 11 variables described in what follows:

  * Code of the meteorological station (always constant, since the data is regarded to Porto Alegre city);
  
  * Date of observation;
  
  * Maximum daily temperature;
  
  * Minimum daily temperature;
  
  * Preciptation level;
  
  * Insolation; (that is, the solar irradiance received in Porto Alegre)
  
  * Evaporation; (measured by the variable Evaporacao_Piche. The name of this variable is a reference to the apparatus used for estimating the evaporation called *Evaporímetro de Piche*)
  
  * Average relative umidity;
  
  * Average wind velocity;

I made the dataset available in a branch from [lps](https://github.com/schnorr/lps) in my
github [camilz/lps](https://github.com/camilz/lps/tree/camilz-patch-1) that is named
*porto-alegre-metereological-data.csv*.

To get the data from my local repository and take a look at it, we could use the following chunk of code

```{r}
file = "porto-alegre-metereological-data.csv"
if(!file.exists(file)){
  download.file("https://github.com/camilz/lps/tree/camilz-patch-1/porto-alegre-metereological-data.csv",
	destfile=file)
}

all_content <- readLines(file);

# All fine to this point
head(all_content, n=10)

# But can't import with the next line
#df <- read.csv(skip_preamble, header=T, sep=",")

library(readr);
df <- read_csv(file, locale = locale(encoding = "UTF-8"), col_types=cols(
  Estacao = col_integer(),
  Data = col_character(),
  Hora = col_factor(levels = c("00:00", "12:00")), # The observations are made at 00:00 and 12:00.
  Precipitacao = col_double(),
  TempMaxima = col_double(),
  TempMinima = col_double(),
  Insolacao = col_double(),
  Evaporacao_Piche = col_double(),
  Temp_Comp_Media = col_double(),
  Umidade_Relativa_Media = col_double(),
  Velocidade_do_Vento_Media = col_double()
));

df;
```


# Questions to be answered

  * There are more than 50 years of daily observations on the dataset. We ask:
      - What are the average temperature;
      - The avarage precipitation;
      - Average insolation;
  * When extreme weather contitions occurred? Do the extreme weather contidions occurs in a regular frequency or are they completely unpredictible?
  * Is there a global trend in Porto Alegre's weather reagarding each of the variables ?
  * How the does the weather changes regarding the seasons? Specificaly:
      - Does the average winter's temperature is getting lower ?
      - Does the average summer's temperature is getting higher ?

